[build]
  command = "yarn build"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[build.environment]
  # Disable secret scan for keys that are meant to be public
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_MEASUREMENT_ID,REACT_APP_STRIPE_PUBLISHABLE_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200