export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "SET_CATEGORIES_START",
  FETCH_CATEGORIES_FAILED: "SET_CATEGORIES_FAILED",
  FETCH_CATEGORIES_SUCCESS: "SET_CATEGORIES_IS_SUCCESS",
};
